
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-30T18:43:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1307bc19e5c54d7bd8f6bba0d1c84a736a72c7ba",
 "version": "0.12.1+73.g1307bc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
