
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-04T13:23:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aee97e555971a8995e59f37efb092b694214b5d7",
 "version": "0.12.1+103.gaee97e5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
