
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-11T11:39:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3136f9688d555bc1c66692ea35e81f21cb4df65f",
 "version": "0.13.0+18.g3136f96"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
